# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  cv:
    desc: Generate a CV from an input TOML file
    requires:
      vars: [file]
    vars:
      format: '{{.format | default "pdf"}}'
    cmds:
      - uv run cv-generator {{.file}} {{.format}}
    silent: true

  cover-letter:
    desc: Generate a cover letter from an input TOML file
    requires:
      vars: [file]
    vars:
      format: '{{.format | default "pdf"}}'
    cmds:
      - uv run cv-generator {{.file}} {{.format}}
    silent: true
